on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: false
        type: string
        default: "."
      pypi-user:
        description: "username to use for accessing myome pypi server"
        required: false
        type: string
        default: "github_cicd"

    secrets:
      aws-access-key-id: 
        description: "SHR_ECR_CI_ACCESS_KEY_ID as created by terraform and stored in secrets manager"
        required: true       
      aws-secret-access-key: 
        description: "SHR_ECR_CI_SECRET_ACCESS_KEY as created by terraform and stored in secrets manager"
        required: true 
      pypi-pw:
        description: "SHR_PYPI_CICD_PWD password for accessing myome pypi server"
        required: false


jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: rlespinasse/github-slug-action@v3.x
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
        IMAGE_TAG: ${{ github.ref_name }}
        SHR_PYPI_CICD_USR: ${{ inputs.pypi-user}}
        SHR_PYPI_CICD_PWD: ${{ secrets.pypi-pw }}
      run: |
        export DOCKER_BUILDKIT=1
        docker build --build-arg SHR_PYPI_CICD_PWD=$SHR_PYPI_CICD_PWD -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{ inputs.dockerfile_path }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
